MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_wide_resnet_backbone"   
    FREEZE_AT: 2                      
  RESNETS:
    DEPTH: 50                           
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]

